export const HOME = "/";
export const AIRISDASHBOARD = "/dashboard";
export const PROJECTS = "/projects";
export const REPORTS = "/reports";
export const BUDGET = "/budget";
export const PROJECTDETAILS = "/projects/:id";
export const ABOUT = "/about"
export const CONTACT = "/contact"
export const FEATURE = "/feature"
export const SIGNUP = "/signup"
export const SIGNIN = "/signin"
// export const PROJECTS = "/projects";